permalink = "/en/:year-:month-:day-:title"
future = true # show future post, posts might be confusingly hidden through different timezones otherwise
plugins = [ "jekyll-sitemap" ]
include = [ ".well-known" ] # include .well-known for flathub verification
exclude = [ "tools", "venv" ] # the tools directory contains cached files downloaded from transifex, ignore it

# the following lines are to make the option {{ page.is_post }} available, thanks to
# https://stackoverflow.com/questions/18675610/jekyll-change-layout-if-page-is-a-post
[[defaults]]
[defaults.scope]
path = "" # empty string for all files

[defaults.values]
layout = "default"

[[defaults]]
[defaults.scope]
path = "" # empty string for all files
type = "posts" # limit to posts

[defaults.values]
is_post = true # automatically set is_post=true for all posts
lang = "en"

[kramdown]
auto_ids = true # auto-generate ID's for headings

[sass]
style = "compressed"
