#!/usr/bin/env python3


# the structure of the help files is:
# - ANY_DIR/help/LANG/help.html  (files generated by deltachat-pages)
# - ANY_DIR/help/help.css  (file is should be provided by deltachat-UI, not generated by deltachat-pages)


from pathlib import Path
from shutil import copyfile
import os
import re


# list all files that should go to the local help here.
# the path should be the path used eg. in the <img> tag.
linked_files = ["../assets/home/delta-what-optim.png"]


def read_file(filename):
    f = open(filename, 'r')
    content = f.read()
    f.close()
    return content


def write_file(filename, content):
    f = open(filename, 'w')
    f.write(content)
    f.close()


def generate_file(destdir, lang, file):
    print("generate local help in " + destdir + "/" + lang + "/" + file)

    content = read_file("../_site/" + lang + "/" + file)

    content = re.sub(r"^.*<div id=\"content\">.*<h1>.*?</h1>.*?<ul.*?>",
                       "<!DOCTYPE html>\n"
                     + "<html>"
                     +   "<head>"
                     +     "<meta charset=\"UTF-8\" />"
                     +     "<link rel=\"stylesheet\" href=\"../help.css\" />"
                     +   "</head>"
                     +   "<body>"
                     +     "<ul id=\"top\">",
                     content,
                     flags=re.MULTILINE|re.DOTALL)

    content = re.sub(r"</div>.*?</body>.*</html>.*$",
                         "</body>"
                     + "</html>",
                     content,
                     flags=re.MULTILINE|re.DOTALL)

    for linked_file in linked_files:
        local_file = "../" + linked_file.split("/")[-1]
        content = re.sub(linked_file, local_file, content)

    write_file(destdir + "/" + lang + "/" + file, content)


def generate_lang(destdir, lang):
    os.makedirs(destdir + "/" + lang, exist_ok=True)
    generate_file(destdir, lang, "help.html")


def generate_help(destdir):
    generate_lang(destdir, "de")
    generate_lang(destdir, "en")
    generate_lang(destdir, "es")
    generate_lang(destdir, "it")
    generate_lang(destdir, "nl")
    generate_lang(destdir, "sq")
    for linked_file in linked_files:
        local_file = destdir + "/" + linked_file.split("/")[-1]
        copyfile(linked_file, local_file)


if __name__ == "__main__":

    # if we're not inside the tools directory, go in
    if Path('tools').exists():
        os.chdir('tools')

    generate_help("../../deltachat-android/assets/help")
