#!/bin/bash

# this script provides some tool needed to translate the homepage.
# For dependencies, it needs python3 and python3-massedit, which you can install with `pip install massedit`.

# before you can use this script the first time, you have to initialize Transifex in this folder:
# $ tx init --user=api --pass=<your api token>
# you may also need `txt2po`, get it by `sudo apt install translate-toolkit`

# after that, call `./t-dance create-po-sources` to rebuild all non-english markdown files
# from the translations provided by transifex users

# call `./t-dance push` pushes the english markdown files to transifex

# the hidden `.tx` folder was generated by the following command:
# $ tx set --auto-remote https://www.transifex.com/projects/p/delta-chat-pages/

# common information about the Transifex CLI client can be found at:
# https://docs.transifex.com/client/

set -e

sfiles=(blog contribute community-standards donate download help imprint index references verify-downloads serverguide)
tlangs=(ca cs de es fr gl id it nl pl pt pt_BR ru sk sq tr uk zh_CN)  # do not add `en` to this list


pull_po_translations_from_tx() {
	rm -r translations || true

	# instead of passing --all to the tx command, create the files we're interested in; this is more than twice faster
	mkdir "translations"
	mkdir "translations/delta-chat-pages.yml"
	for sfile in ${sfiles[@]}; do
	  mkdir "translations/delta-chat-pages.${sfile}po"
	  for tlang in ${tlangs[@]}; do
	    touch "translations/delta-chat-pages.yml/${tlang}.yml"
	    touch "translations/delta-chat-pages.${sfile}po/${tlang}.po"
	  done
	done

	tx pull --translations --force

	for tlang in ${tlangs[@]}; do
	  echo "Converting ${tlang} ..."
	  for sfile in ${sfiles[@]}; do
			pofile="../${tlang}/${sfile}.po"
			cp "translations/delta-chat-pages.${sfile}po/${tlang}.po" $pofile
		done
		cp "translations/delta-chat-pages.yml/${tlang}.yml" "../_data/lang/${tlang}.yml"
	done
}


push_po_sources_to_tx() {
	branch=$(git rev-parse --abbrev-ref HEAD)
	echo $branch
	git status
	if [ -z $branch ] || [ $branch != "main" ]; then
		echo "ERROR: push is only allowed on main, there is a high risk to delete existing translations otherwise"
		exit 1
	fi
	tx push -s
}


create_po_sources() {
	for sfile in ${sfiles[@]}; do
		mkdir -p "translations/delta-chat-pages.${sfile}po"
		txt2po --progress=none "../en/${sfile}.md" "translations/delta-chat-pages.${sfile}po/en.po"
	done
	# sic: for whatever reason, the file is en.yaml and not .yml as everywhere else
	mkdir translations/delta-chat-pages.yml || true
	cp "../_data/lang/en.yaml" "translations/delta-chat-pages.yml/en.yml"
}


create_markdown_files() {
	echo "Creating markdown files from the translated po-files ..."
	for sfile in ${sfiles[@]}; do
		for tlang in ${tlangs[@]}; do
			pofile="../${tlang}/${sfile}.po"
			mdfile="../${tlang}/${sfile}.md"
			po2txt --progress=none --template="../en/${sfile}.md" $pofile $mdfile
			python3 -m massedit -e "re.sub(r'lang: [a-z][a-z](_[A-Z][A-Z])?', 'lang: ${tlang}', line)" -w $mdfile
			#sed -i "" "s/lang: [a-z][a-z]/lang: ${tlang:0:2}/" $mdfile # correct used layout - for some reasons, [a-z]{2,} does not work on sed-mac
		done
	done	
}


create_html_files() {
  # create html files from markdown
  cd ..
  bundle exec jekyll build
  rm -r result || true
  mv _site result
  cd tools
}


reset_markdown_files() {
	for tlang in ${tlangs[@]}; do
		git checkout "../${tlang}/"
	done
}


# convenience: allow calling as ./tools/t-dance.sh from the root dir
cd_back="false"
if [ -d "tools" ]; then
	cd tools
	cd_back="true"
fi


# normal usage
if [ $1 == "pull" ]; then
	pull_po_translations_from_tx
	create_markdown_files
	create_html_files
	cd ..
	./tools/check-translations.sh
	cd tools
elif [ $1 == "push--do-this-only-from-main" ]; then
	create_po_sources
	push_po_sources_to_tx
# debug usage
elif [ $1 == "create-po-sources" ]; then
	create_po_sources
elif [ $1 == "create-md" ]; then
	create_markdown_files	
	create_html_files
elif [ $1 == "reset-md" ]; then
	reset_markdown_files
	create_html_files
else
	echo "pull translations: ./t-dance pull"
	echo "push sources:      ./t-dance push--do-this-only-from-main"
	echo "debug usage:       ./t-dance {create-po-sources|create-md|reset-md}"
	echo "to push a single language, copy the files to translations/delta-chat-pages.<file>po/<lang>.po and call: tx push -t -l <lang>"
fi


if [ $cd_back == "true" ]; then
	cd ..
fi
